# Import necessary libraries

In [1]:

import pandas as pd
import sys
import os
import numpy as np

## Adjust the path to point to the 'scripts' directory

In [3]:
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '../../scripts')))
from model_training import (data_cleaning,data_preparation, split_data, linear_regression_model, random_forest_model, xgboost_model, evaluate_model, feature_importance_shap
)

# Load data

In [4]:
file_path = '../../data/MachineLearningRating_v3.txt'
# Replace delimiter with the correct one
data = pd.read_csv(file_path, delimiter='|')  # Change delimiter as needed

# Display the first few rows of the dataframe
data.head()

C:\Users\habteyes.asfaw\AppData\Local\Temp\ipykernel_18948\607214028.py:3: DtypeWarning: Columns (32,37) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file_path, delimiter='|')  # Change delimiter as needed

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [5]:
cleaned_data = data_cleaning(data)

NameError: name 'np' is not defined

# Step 1: Data Preparation

In [6]:
prepared_data = data_preparation(data)